#ifndef DEFINE_AUXV_TYPE
#error "This file is intended for textual inclusion with the DEFINE_AUXV_TYPE macro defined"
#endif

DEFINE_AUXV_TYPE(AT_NULL, "AT_NULL", "End of vector"),
DEFINE_AUXV_TYPE(AT_IGNORE, "AT_IGNORE", "Entry should be ignored"),
DEFINE_AUXV_TYPE(AT_EXECFD, "AT_EXECFD", "File descriptor of program"),
DEFINE_AUXV_TYPE(AT_PHDR, "AT_PHDR", "Program headers for program"),
DEFINE_AUXV_TYPE(AT_PHENT, "AT_PHENT", "Size of program header entry"),
DEFINE_AUXV_TYPE(AT_PHNUM, "AT_PHNUM", "Number of program headers"),
DEFINE_AUXV_TYPE(AT_PAGESZ, "AT_PAGESZ", "System page size"),
DEFINE_AUXV_TYPE(AT_BASE, "AT_BASE", "Base address of interpreter"),
DEFINE_AUXV_TYPE(AT_FLAGS, "AT_FLAGS", "Flags"),
DEFINE_AUXV_TYPE(AT_ENTRY, "AT_ENTRY", "Entry point of program"),
DEFINE_AUXV_TYPE(AT_NOTELF, "AT_NOTELF", "Program is not ELF"),
DEFINE_AUXV_TYPE(AT_UID, "AT_UID", "Real user ID"),
DEFINE_AUXV_TYPE(AT_EUID, "AT_EUID", "Effective user ID"),
DEFINE_AUXV_TYPE(AT_GID, "AT_GID", "Real group ID"),
DEFINE_AUXV_TYPE(AT_EGID, "AT_EGID", "Effective group ID"),
DEFINE_AUXV_TYPE(AT_PLATFORM, "AT_PLATFORM", "String identifying platform"),
DEFINE_AUXV_TYPE(AT_HWCAP, "AT_HWCAP", "Machine-dependent CPU capability hints"),
DEFINE_AUXV_TYPE(AT_CLKTCK, "AT_CLKTCK", "Frequency of times()"),
DEFINE_AUXV_TYPE(AT_FPUCW, "AT_FPUCW", "Used FPU control word"),
DEFINE_AUXV_TYPE(AT_DCACHEBSIZE, "AT_DCACHEBSIZE", "Data cache block size"),
DEFINE_AUXV_TYPE(AT_ICACHEBSIZE, "AT_ICACHEBSIZE", "Instruction cache block size"),
DEFINE_AUXV_TYPE(AT_UCACHEBSIZE, "AT_UCACHEBSIZE", "Unified cache block size"),
DEFINE_AUXV_TYPE(AT_IGNOREPPC, "AT_IGNOREPPC", "Entry should be ignored (PowerPC)"),
DEFINE_AUXV_TYPE(AT_SECURE, "AT_SECURE", "Boolean, was exec setuid-like?"),
DEFINE_AUXV_TYPE(AT_BASE_PLATFORM, "AT_BASE_PLATFORM", "String identifying real platform"),
DEFINE_AUXV_TYPE(AT_RANDOM, "AT_RANDOM", "Address of 16 random bytes"),
DEFINE_AUXV_TYPE(AT_HWCAP2, "AT_HWCAP2", "Extension of AT_HWCAP"),
DEFINE_AUXV_TYPE(AT_EXECFN, "AT_EXECFN", "File name of executable"),
DEFINE_AUXV_TYPE(AT_SYSINFO, "AT_SYSINFO", "Entry point to syscall implementation"),
DEFINE_AUXV_TYPE(AT_SYSINFO_EHDR, "AT_SYSINFO_EHDR", "System-supplied DSO's ELF header"),
DEFINE_AUXV_TYPE(AT_L1I_CACHESHAPE, "AT_L1I_CACHESHAPE", "Shape of L1 instruction cache"),
DEFINE_AUXV_TYPE(AT_L1D_CACHESHAPE, "AT_L1D_CACHESHAPE", "Shape of L1 data cache"),
DEFINE_AUXV_TYPE(AT_L2_CACHESHAPE, "AT_L2_CACHESHAPE", "Shape of L2 cache"),
DEFINE_AUXV_TYPE(AT_L3_CACHESHAPE, "AT_L3_CACHESHAPE", "Shape of L3 cache"),
DEFINE_AUXV_TYPE(AT_L1I_CACHESIZE, "AT_L1I_CACHESIZE", "Size of L1 instruction cache"),
DEFINE_AUXV_TYPE(AT_L1I_CACHEGEOMETRY, "AT_L1I_CACHEGEOMETRY", "Geometry of L1 instruction cache"),
DEFINE_AUXV_TYPE(AT_L1D_CACHESIZE, "AT_L1D_CACHESIZE", "Size of L1 data cache"),
DEFINE_AUXV_TYPE(AT_L1D_CACHEGEOMETRY, "AT_L1D_CACHEGEOMETRY", "Geometry of L1 data cache"),
DEFINE_AUXV_TYPE(AT_L2_CACHESIZE, "AT_L2_CACHESIZE", "Size of L2 cache"),
DEFINE_AUXV_TYPE(AT_L2_CACHEGEOMETRY, "AT_L2_CACHEGEOMETRY", "Geometry of L2 cache"),
DEFINE_AUXV_TYPE(AT_L3_CACHESIZE, "AT_L3_CACHESIZE", "Size of L3 cache"),
DEFINE_AUXV_TYPE(AT_L3_CACHEGEOMETRY, "AT_L3_CACHEGEOMETRY", "Geometry of L3 cache"),
DEFINE_AUXV_TYPE(AT_MINSIGSTKSZ, "AT_MINSIGSTKSZ", "Minimum stack size for signal delivery"),
DEFINE_AUXV_TYPE(AT_RSEQ_FEATURE_SIZE, "AT_RSEQ_FEATURE_SIZE", "rseq supported feature size"),
DEFINE_AUXV_TYPE(AT_RSEQ_ALIGN, "AT_RSEQ_ALIGN", "rseq allocation alignment"),